### ISSUE TITLE
develop build broken

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/serialization#107]
Hi Robert,

Something just broke the develop build on all msvc versions prior to 14.1, my appveyor CI tests are all failing in:

```
[00:10:40] compile-c-c++ ..\..\..\bin.v2\libs\serialization\build\9218ae764f8240b7321ebd1ea2d19264\xml_grammar.obj
[00:10:40] xml_grammar.cpp
[00:10:40] ..\..\..\boost/archive/iterators/xml_unescape.hpp(114) : fatal error C1063: compiler limit : compiler stack overflow
[00:10:40] Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.exe.  You will be prompted to send an error report to Microsoft later.
[00:10:41] 
[00:10:41]     call "..\..\..\bin.v2\standalone\msvc\0b00851a9d61d40fad804f9053579ad8\msvc-setup.bat" x86 >nul
[00:10:41]  cl /Zm800 -nologo @"..\..\..\bin.v2\libs\serialization\build\9218ae764f8240b7321ebd1ea2d19264\xml_grammar.obj.rsp" 
```

**Comment by robertramey** [comment]
OK - I think I fixed this

**Comment by jeking3** [comment]
Seeing the same thing with MSVC2010 builds in uuid:
```
[00:03:41] compile-c-c++ bin.v2\libs\serialization\build\msvc-10.0\release\cxxstd-03-iso\link-static\threading-multi\xml_grammar.obj
[00:03:41] xml_grammar.cpp
[00:03:41] .\boost/archive/iterators/xml_unescape.hpp(121) : fatal error C1063: compiler limit : compiler stack overflow
[00:03:41] Internal Compiler Error in c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe.  You will be prompted to send an error report to Microsoft later.
[00:03:41] 
```

I will try to update to the latest serialization and see what happens.

**Comment by jeking3** [comment]
Still seeing this as of last night:

https://ci.appveyor.com/project/jeking3/uuid-gaamf/build/1.0.116-develop/job/b1py91x9f3rs5wne

**Comment by jzmaddock** [comment]
Me too.

However, this can be fixed by making `xml_unescape<>::drain` and `xml_unescape::drain_residue` class inline.

The problem appears to be the definition of `xml_unescape::value_type` which actually looks kind of circular to me:

```
        typedef typename this_t::value_type value_type;
```

which defines value_type in terms of itself?

**Comment by jzmaddock** [comment]
Update, using:

```
        typedef int value_type;
```

Does fix the issue, but the BOOST_WORKAROUND uses the wrong value, MSVC-14 has BOOST_MSVC == 1900.

I still don't see how:

```
typedef typename this_t::value_type value_type;
```

can compile though...

**Comment by jeking3** [comment]
Still happening:
```
[00:03:21] .\boost/archive/iterators/xml_unescape.hpp(121) : fatal error C1063: compiler limit : compiler stack overflow
[00:03:21] Internal Compiler Error in c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe.  You will be prompted to send an error report to Microsoft later.
[00:03:23] 
[00:03:23]     call "bin.v2\standalone\msvc\msvc-10.0\msvc-setup.bat" x86 >nul
[00:03:23]  cl /Zm800 -nologo @"bin.v2\libs\serialization\build\msvc-10.0\release\cxxstd-03-iso\threading-multi\xml_grammar.obj.rsp" 
[00:03:23] 
[00:03:23] ...failed compile-c-c++ bin.v2\libs\serialization\build\msvc-10.0\release\cxxstd-03-iso\threading-multi\xml_grammar.obj...
```

ref: https://ci.appveyor.com/project/jeking3/date-time-1evbf/build/job/w89rydna0rgy8bn4

**Comment by jzmaddock** [comment]
Ping?  Any chance the MSVC workaround version  can be changed to the correct value (1900)?

**Comment by jzmaddock** [comment]
Confirmed this is now fixed in develop.  Thanks!
